HEADER_BYTES = 4
TYPE_BYTES = 1
DATA_LEN_BYTES = HEADER_BYTES - TYPE_BYTES
BYTEORDER = "little"
RECEIVE_LEN = 4096
MSG_LEN_BYTES = 2
MAX_DATA_LEN = 2 ** (DATA_LEN_BYTES * 8) - 1  # Data can be up to 1677 KB or 1.6 MB
MAX_MSG_SIZE = 2 ** (MSG_LEN_BYTES * 8) - 1  # Message can be up to 65 KB
